---

- name: Add user to group
  user:
    name: jenkins
    groups: vagrant
    append: yes
  become: yes

- name: Get Jenkins crumb
  uri:
    user: jenkins
    password: "{{ admin_user_pass }}"
    force_basic_auth: yes
    url: "http://127.0.0.1:8080/crumbIssuer/api/json"
    return_content: yes
  register: crumb_token
  until: crumb_token.content.find('Please wait while Jenkins is getting ready') == -1
  retries: 10
  delay: 5

- name: Set crumb token
  set_fact:
    crumb: "{{ crumb_token.json.crumbRequestField }}={{ crumb_token.json.crumb }}"

- name: Create Jenkins job for apache ami
  jenkins_job:
    config: "{{ lookup('template', 'pipeline.xml.j2') }}"
    name: ansible-helloworld
    url: http://localhost:8080
    user: jenkins
    password: "{{ admin_user_pass }}"

- name: Get user token
  jenkins_script:
    script: |
        import jenkins.model.*;
        import jenkins.security.*;
        user = hudson.model.User.get('test3')
        prop = user.getProperty(jenkins.security.ApiTokenProperty.class)
        prop.changeApiToken()
        println(prop.getApiTokenInsecure())
    user: jenkins
    password: "{{ admin_user_pass }}"
  register: user_token

- name: print token jenkins
  debug:
    var: user_token.output

- name: Run build of a project in Jenkins
  uri:
    url: "http://127.0.0.1:8080/job/ansible-helloworld/build?token={{ crumb_token.json.crumb }}"
    method: POST
    user: jenkins
    password: "{{ user_token.output }}"
    force_basic_auth: yes
    use_proxy: false
    status_code: 201
    validate_certs: false
