---

- name: Download Java JDK
  get_url:
    url: https://s3-us-west-2.amazonaws.com/lpetryshyn/java/jdk-8u191-linux-x64.rpm
    dest: /tmp/jdk-8u191-linux-x64.rpm
    headers: 'Cookie: oraclelicense=accept-securebackup-cookie'

- name: Install Java JDK rpm from a local file
  yum:
    name: /tmp/jdk-8u191-linux-x64.rpm
    state: present
  become: yes
