---
deploy_user: deployeer
deploy_user_pass: deployer
artifactory_deployer: jenkins
artifactory_deployer_pass: passwd
admin_user_pass: passwd
jenkins_plugins:
  - ansible
  - lockable-resources
  - ace-editor
  - docker-commons
  - docker-workflow
  - gradle
  - ant
  - ivy
  - antisamy-markup-formatter
  - apache-httpcomponents-client-4-api
  - artifactory
  - authentication-tokens
  - aws-java-sdk
  - bouncycastle-api
  - branch-api
  - build-timeout
  - cloudbees-credentials
  - cloudbees-folder
  - codedeploy
  - command-launcher
  - config-file-provider
  - credentials
  - credentials-binding
  - dependencyanalyzer
  - deploy
  - display-url-api
  - durable-task
  - email-ext
  - envinject
  - envinject-api
  - external-monitor-job
  - git
  - git-client
  - git-server
  - github
  - github-api
  - github-branch-source
  - gitlab-oauth
  - gitlab-plugin
  - handlebars
  - jackson2-api
  - javadoc
  - jdk-tool
  - jquery-detached
  - jsch
  - junit
  - ldap
  - m2release
  - mailer
  - mapdb-api
  - matrix-auth
  - matrix-project
  - maven-dependency-update-trigger
  - maven-plugin
  - momentjs
  - pam-auth
  - pipeline-build-step
  - pipeline-github-lib
  - pipeline-graph-analysis
  - pipeline-input-step
  - pipeline-maven
  - pipeline-milestone-step
  - pipeline-model-api
  - pipeline-model-declarative-agent
  - pipeline-model-definition
  - pipeline-model-extensions
  - pipeline-rest-api
  - pipeline-stage-step
  - pipeline-stage-tags-metadata
  - pipeline-stage-view
  - plain-credentials
  - repository-connector
  - resource-disposer
  - scm-api
  - script-security
  - shared-objects
  - ssh-credentials
  - ssh-slaves
  - structs
  - subversion
  - timestamper
  - token-macro
  - workflow-aggregator
  - workflow-api
  - workflow-basic-steps
  - workflow-cps
  - workflow-cps-global-lib
  - workflow-durable-task-step
  - workflow-job
  - workflow-multibranch
  - workflow-scm-step
  - workflow-step-api
  - workflow-support
  - ws-cleanup
