---

- name: Install MySQL and prerequesites
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - python-mysqldb
    - mysql-server

- name: install Mysql-python
  pip:
    name: mysql-python

- name: Start the MySQL service
  action: service name=mysql state=started

- name: Remove the test database
  mysql_db: name=test state=absent

- name: Create aifactory user for mysql
  mysql_user: user="artifactory" host="%" password={{mysql_root_password}} priv=*.*:ALL,GRANT

- name: Ensure anonymous users are not in the database
  mysql_user: user='' host=$item state=absent
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy .my.cnf file with root password credentials
  template: src=.my.cnf.j2 dest=/etc/mysql/my.cnf owner=root mode=0600

- name: Update mysql root password for all root accounts
  mysql_user: name=root host={{item}} password={{mysql_root_password}}
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
